// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWlxrRB-c59SpVaIPUtnTFjeWLKlP8QE',
    appId: '1:130794354324:web:3930804930f9103e5b6681',
    messagingSenderId: '130794354324',
    projectId: 'myflutterchat-1596f',
    authDomain: 'myflutterchat-1596f.firebaseapp.com',
    databaseURL: 'https://myflutterchat-1596f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myflutterchat-1596f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnzC5at-VHaKgj0F5q78qMzDGzZdB5Kbs',
    appId: '1:130794354324:android:2561c1decbb9e5245b6681',
    messagingSenderId: '130794354324',
    projectId: 'myflutterchat-1596f',
    databaseURL: 'https://myflutterchat-1596f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myflutterchat-1596f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8BYW0j2o0twosSMq-TigISCR1xRilf5Y',
    appId: '1:130794354324:ios:4e7dbe8bf567e7c45b6681',
    messagingSenderId: '130794354324',
    projectId: 'myflutterchat-1596f',
    databaseURL: 'https://myflutterchat-1596f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myflutterchat-1596f.appspot.com',
    iosBundleId: 'com.example.myFlutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8BYW0j2o0twosSMq-TigISCR1xRilf5Y',
    appId: '1:130794354324:ios:4e7dbe8bf567e7c45b6681',
    messagingSenderId: '130794354324',
    projectId: 'myflutterchat-1596f',
    databaseURL: 'https://myflutterchat-1596f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myflutterchat-1596f.appspot.com',
    iosBundleId: 'com.example.myFlutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGWlxrRB-c59SpVaIPUtnTFjeWLKlP8QE',
    appId: '1:130794354324:web:14485a238c02e3a75b6681',
    messagingSenderId: '130794354324',
    projectId: 'myflutterchat-1596f',
    authDomain: 'myflutterchat-1596f.firebaseapp.com',
    databaseURL: 'https://myflutterchat-1596f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myflutterchat-1596f.appspot.com',
  );
}
